package model.EO;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 07 19:51:55 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcInspectionProcessLineEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RollNumber {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getRollNumber();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setRollNumber((String)value);
            }
        }
        ,
        InspectionMachineNumber {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getInspectionMachineNumber();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setInspectionMachineNumber((String)value);
            }
        }
        ,
        RollQuantity {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getRollQuantity();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setRollQuantity((Number)value);
            }
        }
        ,
        TotalFaults {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getTotalFaults();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setTotalFaults((Number)value);
            }
        }
        ,
        FaultsPer100Sq {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getFaultsPer100Sq();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setFaultsPer100Sq((Number)value);
            }
        }
        ,
        Grade {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getGrade();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setGrade((String)value);
            }
        }
        ,
        InspectionDate {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getInspectionDate();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setInspectionDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        LastUpdatedLogin {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getLastUpdatedLogin();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setLastUpdatedLogin((String)value);
            }
        }
        ,
        OrgId {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        MfgOrgId {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getMfgOrgId();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setMfgOrgId((Number)value);
            }
        }
        ,
        BatchNumber {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getBatchNumber();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setBatchNumber((String)value);
            }
        }
        ,
        BuyerName {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getBuyerName();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setBuyerName((String)value);
            }
        }
        ,
        FinishingJobNumber {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getFinishingJobNumber();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setFinishingJobNumber((String)value);
            }
        }
        ,
        ItemCode {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getItemCode();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getItemDescription();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        JobQuantity {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getJobQuantity();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setJobQuantity((Number)value);
            }
        }
        ,
        PpNumber {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getPpNumber();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setPpNumber((String)value);
            }
        }
        ,
        WoNumber {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getWoNumber();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setWoNumber((String)value);
            }
        }
        ,
        InspectionProcessLineId {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getInspectionProcessLineId();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setInspectionProcessLineId((Number)value);
            }
        }
        ,
        InspectionProcessId {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getInspectionProcessId();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setInspectionProcessId((BigDecimal)value);
            }
        }
        ,
        CutableWidth {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getCutableWidth();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setCutableWidth((BigDecimal)value);
            }
        }
        ,
        FinishWidth {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getFinishWidth();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setFinishWidth((BigDecimal)value);
            }
        }
        ,
        Kgs {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getKgs();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setKgs((BigDecimal)value);
            }
        }
        ,
        PwcOdmInspPrcFaultEntriesEO {
            public Object get(PwcInspectionProcessLineEOImpl obj) {
                return obj.getPwcOdmInspPrcFaultEntriesEO();
            }

            public void put(PwcInspectionProcessLineEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PwcInspectionProcessLineEOImpl object);

        public abstract void put(PwcInspectionProcessLineEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


//    public static final int PWCINSPECTIONPROCESSHEADEREO = AttributesEnum.PwcInspectionProcessHeaderEO.index();


    public static final int ROLLNUMBER = AttributesEnum.RollNumber.index();
    public static final int INSPECTIONMACHINENUMBER = AttributesEnum.InspectionMachineNumber.index();
    public static final int ROLLQUANTITY = AttributesEnum.RollQuantity.index();
    public static final int TOTALFAULTS = AttributesEnum.TotalFaults.index();
    public static final int FAULTSPER100SQ = AttributesEnum.FaultsPer100Sq.index();
    public static final int GRADE = AttributesEnum.Grade.index();
    public static final int INSPECTIONDATE = AttributesEnum.InspectionDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDLOGIN = AttributesEnum.LastUpdatedLogin.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int MFGORGID = AttributesEnum.MfgOrgId.index();
    public static final int BATCHNUMBER = AttributesEnum.BatchNumber.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int FINISHINGJOBNUMBER = AttributesEnum.FinishingJobNumber.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int JOBQUANTITY = AttributesEnum.JobQuantity.index();
    public static final int PPNUMBER = AttributesEnum.PpNumber.index();
    public static final int WONUMBER = AttributesEnum.WoNumber.index();
    public static final int INSPECTIONPROCESSLINEID = AttributesEnum.InspectionProcessLineId.index();
    public static final int INSPECTIONPROCESSID = AttributesEnum.InspectionProcessId.index();
    public static final int CUTABLEWIDTH = AttributesEnum.CutableWidth.index();
    public static final int FINISHWIDTH = AttributesEnum.FinishWidth.index();
    public static final int KGS = AttributesEnum.Kgs.index();
    public static final int PWCODMINSPPRCFAULTENTRIESEO = AttributesEnum.PwcOdmInspPrcFaultEntriesEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcInspectionProcessLineEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.EO.PwcInspectionProcessLineEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for RollNumber, using the alias name RollNumber.
     * @return the RollNumber
     */
    public String getRollNumber() {
        return (String)getAttributeInternal(ROLLNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RollNumber.
     * @param value value to set the RollNumber
     */
    public void setRollNumber(String value) {
        setAttributeInternal(ROLLNUMBER, value);
    }

    /**
     * Gets the attribute value for InspectionMachineNumber, using the alias name InspectionMachineNumber.
     * @return the InspectionMachineNumber
     */
    public String getInspectionMachineNumber() {
        return (String)getAttributeInternal(INSPECTIONMACHINENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for InspectionMachineNumber.
     * @param value value to set the InspectionMachineNumber
     */
    public void setInspectionMachineNumber(String value) {
        setAttributeInternal(INSPECTIONMACHINENUMBER, value);
    }


    /**
     * Gets the attribute value for RollQuantity, using the alias name RollQuantity.
     * @return the RollQuantity
     */
    public Number getRollQuantity() {
        return (Number)getAttributeInternal(ROLLQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RollQuantity.
     * @param value value to set the RollQuantity
     */
    public void setRollQuantity(Number value) {
        setAttributeInternal(ROLLQUANTITY, value);
    }

    /**
     * Gets the attribute value for TotalFaults, using the alias name TotalFaults.
     * @return the TotalFaults
     */
    public Number getTotalFaults() {
        return (Number)getAttributeInternal(TOTALFAULTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalFaults.
     * @param value value to set the TotalFaults
     */
    public void setTotalFaults(Number value) {
        setAttributeInternal(TOTALFAULTS, value);
    }

    /**
     * Gets the attribute value for FaultsPer100Sq, using the alias name FaultsPer100Sq.
     * @return the FaultsPer100Sq
     */
    public Number getFaultsPer100Sq() {
        return (Number)getAttributeInternal(FAULTSPER100SQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for FaultsPer100Sq.
     * @param value value to set the FaultsPer100Sq
     */
    public void setFaultsPer100Sq(Number value) {
        setAttributeInternal(FAULTSPER100SQ, value);
    }

    /**
     * Gets the attribute value for Grade, using the alias name Grade.
     * @return the Grade
     */
    public String getGrade() {
        return (String)getAttributeInternal(GRADE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Grade.
     * @param value value to set the Grade
     */
    public void setGrade(String value) {
        setAttributeInternal(GRADE, value);
    }

    /**
     * Gets the attribute value for InspectionDate, using the alias name InspectionDate.
     * @return the InspectionDate
     */
    public Date getInspectionDate() {
        return (Date)getAttributeInternal(INSPECTIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InspectionDate.
     * @param value value to set the InspectionDate
     */
    public void setInspectionDate(Date value) {
        setAttributeInternal(INSPECTIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedLogin, using the alias name LastUpdatedLogin.
     * @return the LastUpdatedLogin
     */
    public String getLastUpdatedLogin() {
        return (String)getAttributeInternal(LASTUPDATEDLOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedLogin.
     * @param value value to set the LastUpdatedLogin
     */
    public void setLastUpdatedLogin(String value) {
        setAttributeInternal(LASTUPDATEDLOGIN, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for MfgOrgId, using the alias name MfgOrgId.
     * @return the MfgOrgId
     */
    public Number getMfgOrgId() {
        return (Number)getAttributeInternal(MFGORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MfgOrgId.
     * @param value value to set the MfgOrgId
     */
    public void setMfgOrgId(Number value) {
        setAttributeInternal(MFGORGID, value);
    }

    /**
     * Gets the attribute value for BatchNumber, using the alias name BatchNumber.
     * @return the BatchNumber
     */
    public String getBatchNumber() {
        return (String)getAttributeInternal(BATCHNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchNumber.
     * @param value value to set the BatchNumber
     */
    public void setBatchNumber(String value) {
        setAttributeInternal(BATCHNUMBER, value);
    }

    /**
     * Gets the attribute value for BuyerName, using the alias name BuyerName.
     * @return the BuyerName
     */
    public String getBuyerName() {
        return (String)getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerName.
     * @param value value to set the BuyerName
     */
    public void setBuyerName(String value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for FinishingJobNumber, using the alias name FinishingJobNumber.
     * @return the FinishingJobNumber
     */
    public String getFinishingJobNumber() {
        return (String)getAttributeInternal(FINISHINGJOBNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinishingJobNumber.
     * @param value value to set the FinishingJobNumber
     */
    public void setFinishingJobNumber(String value) {
        setAttributeInternal(FINISHINGJOBNUMBER, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for ItemDescription, using the alias name ItemDescription.
     * @return the ItemDescription
     */
    public String getItemDescription() {
        return (String)getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDescription.
     * @param value value to set the ItemDescription
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for JobQuantity, using the alias name JobQuantity.
     * @return the JobQuantity
     */
    public Number getJobQuantity() {
        return (Number)getAttributeInternal(JOBQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobQuantity.
     * @param value value to set the JobQuantity
     */
    public void setJobQuantity(Number value) {
        setAttributeInternal(JOBQUANTITY, value);
    }

    /**
     * Gets the attribute value for PpNumber, using the alias name PpNumber.
     * @return the PpNumber
     */
    public String getPpNumber() {
        return (String)getAttributeInternal(PPNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PpNumber.
     * @param value value to set the PpNumber
     */
    public void setPpNumber(String value) {
        setAttributeInternal(PPNUMBER, value);
    }

    /**
     * Gets the attribute value for WoNumber, using the alias name WoNumber.
     * @return the WoNumber
     */
    public String getWoNumber() {
        return (String)getAttributeInternal(WONUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for WoNumber.
     * @param value value to set the WoNumber
     */
    public void setWoNumber(String value) {
        setAttributeInternal(WONUMBER, value);
    }

    /**
     * Gets the attribute value for InspectionProcessLineId, using the alias name InspectionProcessLineId.
     * @return the InspectionProcessLineId
     */
    public Number getInspectionProcessLineId() {
        return (Number)getAttributeInternal(INSPECTIONPROCESSLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InspectionProcessLineId.
     * @param value value to set the InspectionProcessLineId
     */
    public void setInspectionProcessLineId(Number value) {
        setAttributeInternal(INSPECTIONPROCESSLINEID, value);
    }

    /**
     * Gets the attribute value for InspectionProcessId, using the alias name InspectionProcessId.
     * @return the InspectionProcessId
     */
    public BigDecimal getInspectionProcessId() {
        return (BigDecimal)getAttributeInternal(INSPECTIONPROCESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InspectionProcessId.
     * @param value value to set the InspectionProcessId
     */
    public void setInspectionProcessId(BigDecimal value) {
        setAttributeInternal(INSPECTIONPROCESSID, value);
    }

    /**
     * Gets the attribute value for CutableWidth, using the alias name CutableWidth.
     * @return the CutableWidth
     */
    public BigDecimal getCutableWidth() {
        return (BigDecimal)getAttributeInternal(CUTABLEWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutableWidth.
     * @param value value to set the CutableWidth
     */
    public void setCutableWidth(BigDecimal value) {
        setAttributeInternal(CUTABLEWIDTH, value);
    }

    /**
     * Gets the attribute value for FinishWidth, using the alias name FinishWidth.
     * @return the FinishWidth
     */
    public BigDecimal getFinishWidth() {
        return (BigDecimal)getAttributeInternal(FINISHWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinishWidth.
     * @param value value to set the FinishWidth
     */
    public void setFinishWidth(BigDecimal value) {
        setAttributeInternal(FINISHWIDTH, value);
    }

    /**
     * Gets the attribute value for Kgs, using the alias name Kgs.
     * @return the Kgs
     */
    public BigDecimal getKgs() {
        return (BigDecimal)getAttributeInternal(KGS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Kgs.
     * @param value value to set the Kgs
     */
    public void setKgs(BigDecimal value) {
        setAttributeInternal(KGS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPwcOdmInspPrcFaultEntriesEO() {
        return (RowIterator)getAttributeInternal(PWCODMINSPPRCFAULTENTRIESEO);
    }


    /**
     * @param inspectionProcessLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number inspectionProcessLineId) {
        return new Key(new Object[]{inspectionProcessLineId});
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
  /*  public EntityImpl getPwcInspectionProcessHeaderEO() {
        return (EntityImpl)getAttributeInternal(PWCINSPECTIONPROCESSHEADEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
   /* public void setPwcInspectionProcessHeaderEO(EntityImpl value) {
        setAttributeInternal(PWCINSPECTIONPROCESSHEADEREO, value);
    }


    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}
