package model.VO;

import java.math.BigDecimal;

import model.AM.InspectionProcessAMImpl;

import model.EO.PwcInspectionProcessLineEOImpl;

import oracle.adf.model.BindingContext;
import oracle.adf.model.binding.DCDataControl;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 19 18:26:53 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcInspectionProcessLineVORowImpl extends ViewRowImpl {
    
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        InspectionProcessId {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getInspectionProcessId();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setInspectionProcessId((BigDecimal)value);
            }
        }
        ,
        RollNumber {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getRollNumber();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setRollNumber((String)value);
            }
        }
        ,
        InspectionMachineNumber {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getInspectionMachineNumber();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setInspectionMachineNumber((String)value);
            }
        }
        ,
        RollQuantity {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getRollQuantity();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setRollQuantity((Number)value);
            }
        }
        ,
        TotalFaults {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getTotalFaults();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setTotalFaults((Number)value);
            }
        }
        ,
        FaultsPer100Sq {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getFaultsPer100Sq();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setFaultsPer100Sq((Number)value);
            }
        }
        ,
        Grade {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getGrade();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setGrade((String)value);
            }
        }
        ,
        InspectionDate {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getInspectionDate();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setInspectionDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        LastUpdatedLogin {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getLastUpdatedLogin();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedLogin((String)value);
            }
        }
        ,
        OrgId {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        MfgOrgId {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getMfgOrgId();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setMfgOrgId((Number)value);
            }
        }
        ,
        InspectionProcessLineId {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getInspectionProcessLineId();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setInspectionProcessLineId((Number)value);
            }
        }
        ,
        RollQuantityMtr {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getRollQuantityMtr();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setRollQuantityMtr((BigDecimal)value);
            }
        }
        ,
        CutableWidth {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getCutableWidth();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setCutableWidth((BigDecimal)value);
            }
        }
        ,
        FinishWidth {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getFinishWidth();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setFinishWidth((BigDecimal)value);
            }
        }
        ,
        Kgs {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getKgs();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setKgs((BigDecimal)value);
            }
        }
        ,
        GLM {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getGLM();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setGLM((String)value);
            }
        }
        ,
        PwcOdmInspPrcDyeFaultVO {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getPwcOdmInspPrcDyeFaultVO();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmInspPrcGreigeFaultVO {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getPwcOdmInspPrcGreigeFaultVO();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmInspPrcWeaveFaultVO {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getPwcOdmInspPrcWeaveFaultVO();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmInspPrcFaultEntriesVO {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getPwcOdmInspPrcFaultEntriesVO();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        /*PwcOdmInsPrcFaultsTotalVO {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getPwcOdmInsPrcFaultsTotalVO();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,*/
        PwcOdmInsPrcFaultsTotalVO1 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getPwcOdmInsPrcFaultsTotalVO1();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcInspectionProcessHeaderVO {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getPwcInspectionProcessHeaderVO();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GradesLOV1 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getGradesLOV1();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RollNumberLOV1 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getRollNumberLOV1();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MachineNumberLOV1 {
            public Object get(PwcInspectionProcessLineVORowImpl obj) {
                return obj.getMachineNumberLOV1();
            }

            public void put(PwcInspectionProcessLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PwcInspectionProcessLineVORowImpl object);

        public abstract void put(PwcInspectionProcessLineVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int INSPECTIONPROCESSID = AttributesEnum.InspectionProcessId.index();
    public static final int ROLLNUMBER = AttributesEnum.RollNumber.index();
    public static final int INSPECTIONMACHINENUMBER = AttributesEnum.InspectionMachineNumber.index();
    public static final int ROLLQUANTITY = AttributesEnum.RollQuantity.index();
    public static final int TOTALFAULTS = AttributesEnum.TotalFaults.index();
    public static final int FAULTSPER100SQ = AttributesEnum.FaultsPer100Sq.index();
    public static final int GRADE = AttributesEnum.Grade.index();
    public static final int INSPECTIONDATE = AttributesEnum.InspectionDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDLOGIN = AttributesEnum.LastUpdatedLogin.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int MFGORGID = AttributesEnum.MfgOrgId.index();
    public static final int INSPECTIONPROCESSLINEID = AttributesEnum.InspectionProcessLineId.index();
    public static final int ROLLQUANTITYMTR = AttributesEnum.RollQuantityMtr.index();
    public static final int CUTABLEWIDTH = AttributesEnum.CutableWidth.index();
    public static final int FINISHWIDTH = AttributesEnum.FinishWidth.index();
    public static final int KGS = AttributesEnum.Kgs.index();
    public static final int GLM = AttributesEnum.GLM.index();
    public static final int PWCODMINSPPRCDYEFAULTVO = AttributesEnum.PwcOdmInspPrcDyeFaultVO.index();
    public static final int PWCODMINSPPRCGREIGEFAULTVO = AttributesEnum.PwcOdmInspPrcGreigeFaultVO.index();
    public static final int PWCODMINSPPRCWEAVEFAULTVO = AttributesEnum.PwcOdmInspPrcWeaveFaultVO.index();
    public static final int PWCODMINSPPRCFAULTENTRIESVO = AttributesEnum.PwcOdmInspPrcFaultEntriesVO.index();
//    public static final int PWCODMINSPRCFAULTSTOTALVO = AttributesEnum.PwcOdmInsPrcFaultsTotalVO.index();
    public static final int PWCODMINSPRCFAULTSTOTALVO1 = AttributesEnum.PwcOdmInsPrcFaultsTotalVO1.index();
    public static final int PWCINSPECTIONPROCESSHEADERVO = AttributesEnum.PwcInspectionProcessHeaderVO.index();
    public static final int GRADESLOV1 = AttributesEnum.GradesLOV1.index();
    public static final int ROLLNUMBERLOV1 = AttributesEnum.RollNumberLOV1.index();
    public static final int MACHINENUMBERLOV1 = AttributesEnum.MachineNumberLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcInspectionProcessLineVORowImpl() {
    }

    /**
     * Gets PwcInspectionProcessLineEO entity object.
     * @return the PwcInspectionProcessLineEO
     */
    public PwcInspectionProcessLineEOImpl getPwcInspectionProcessLineEO() {
        return (PwcInspectionProcessLineEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for INSPECTION_PROCESS_ID using the alias name InspectionProcessId.
     * @return the INSPECTION_PROCESS_ID
     */
    public BigDecimal getInspectionProcessId() {
        return (BigDecimal) getAttributeInternal(INSPECTIONPROCESSID);
    }

    /**
     * Sets <code>value</code> as attribute value for INSPECTION_PROCESS_ID using the alias name InspectionProcessId.
     * @param value value to set the INSPECTION_PROCESS_ID
     */
    public void setInspectionProcessId(BigDecimal value) {
        setAttributeInternal(INSPECTIONPROCESSID, value);
    }

    /**
     * Gets the attribute value for ROLL_NUMBER using the alias name RollNumber.
     * @return the ROLL_NUMBER
     */
    public String getRollNumber() {
        return (String) getAttributeInternal(ROLLNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLL_NUMBER using the alias name RollNumber.
     * @param value value to set the ROLL_NUMBER
     */
    public void setRollNumber(String value) {
        setAttributeInternal(ROLLNUMBER, value);
    }

    /**
     * Gets the attribute value for INSPECTION_MACHINE_NUMBER using the alias name InspectionMachineNumber.
     * @return the INSPECTION_MACHINE_NUMBER
     */
    public String getInspectionMachineNumber() {
        return (String) getAttributeInternal(INSPECTIONMACHINENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for INSPECTION_MACHINE_NUMBER using the alias name InspectionMachineNumber.
     * @param value value to set the INSPECTION_MACHINE_NUMBER
     */
    public void setInspectionMachineNumber(String value) {
        setAttributeInternal(INSPECTIONMACHINENUMBER, value);
    }

    /**
     * Gets the attribute value for ROLL_QUANTITY using the alias name RollQuantity.
     * @return the ROLL_QUANTITY
     */
    public Number getRollQuantity() {
        return (Number)getAttributeInternal(ROLLQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLL_QUANTITY using the alias name RollQuantity.
     * @param value value to set the ROLL_QUANTITY
     */
    public void setRollQuantity(Number value) {
        setAttributeInternal(ROLLQUANTITY, value);
    }

    /**
     * Gets the attribute value for TOTAL_FAULTS using the alias name TotalFaults.
     * @return the TOTAL_FAULTS
     */
    public Number getTotalFaults() {
        return (Number)getAttributeInternal(TOTALFAULTS);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_FAULTS using the alias name TotalFaults.
     * @param value value to set the TOTAL_FAULTS
     */
    public void setTotalFaults(Number value) {
        setAttributeInternal(TOTALFAULTS, value);
    }

    /**
     * Gets the attribute value for FAULTS_PER_100_SQ using the alias name FaultsPer100Sq.
     * @return the FAULTS_PER_100_SQ
     */
    public Number getFaultsPer100Sq() {
//        return (Number)getAttributeInternal(FAULTSPER100SQ);
        int totalQty = Integer.parseInt(getTotalFaults()!=null?getTotalFaults().toString():"0");
        int inspectedYarn = Integer.parseInt(getRollQuantity()!=null?getRollQuantity().toString():"0");
        int cutableWidth = Integer.parseInt(getCutableWidth()!=null?getCutableWidth().toString():"0");
        if (inspectedYarn!=0 && cutableWidth!=0 && totalQty!=0)
        {
            int result = ((totalQty*3600)/(inspectedYarn*cutableWidth));
            return new Number(result);
        }
        else return new Number(0);
    }

    /**
     * Sets <code>value</code> as attribute value for FAULTS_PER_100_SQ using the alias name FaultsPer100Sq.
     * @param value value to set the FAULTS_PER_100_SQ
     */
    public void setFaultsPer100Sq(Number value) {
        setAttributeInternal(FAULTSPER100SQ, value);
    }

    /**
     * Gets the attribute value for GRADE using the alias name Grade.
     * @return the GRADE
     */
    public String getGrade() {
        return (String) getAttributeInternal(GRADE);
    }

    /**
     * Sets <code>value</code> as attribute value for GRADE using the alias name Grade.
     * @param value value to set the GRADE
     */
    public void setGrade(String value) {
        setAttributeInternal(GRADE, value);
    }

    /**
     * Gets the attribute value for INSPECTION_DATE using the alias name InspectionDate.
     * @return the INSPECTION_DATE
     */
    public Date getInspectionDate() {
        return (Date)getAttributeInternal(INSPECTIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INSPECTION_DATE using the alias name InspectionDate.
     * @param value value to set the INSPECTION_DATE
     */
    public void setInspectionDate(Date value) {
        setAttributeInternal(INSPECTIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @return the LAST_UPDATED_LOGIN
     */
    public String getLastUpdatedLogin() {
        return (String) getAttributeInternal(LASTUPDATEDLOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @param value value to set the LAST_UPDATED_LOGIN
     */
    public void setLastUpdatedLogin(String value) {
        setAttributeInternal(LASTUPDATEDLOGIN, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for MFG_ORG_ID using the alias name MfgOrgId.
     * @return the MFG_ORG_ID
     */
    public Number getMfgOrgId() {
        return (Number)getAttributeInternal(MFGORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for MFG_ORG_ID using the alias name MfgOrgId.
     * @param value value to set the MFG_ORG_ID
     */
    public void setMfgOrgId(Number value) {
        setAttributeInternal(MFGORGID, value);
    }

    /**
     * Gets the attribute value for INSPECTION_PROCESS_LINE_ID using the alias name InspectionProcessLineId.
     * @return the INSPECTION_PROCESS_LINE_ID
     */
    public Number getInspectionProcessLineId() {
        return (Number)getAttributeInternal(INSPECTIONPROCESSLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for INSPECTION_PROCESS_LINE_ID using the alias name InspectionProcessLineId.
     * @param value value to set the INSPECTION_PROCESS_LINE_ID
     */
    public void setInspectionProcessLineId(Number value) {
        setAttributeInternal(INSPECTIONPROCESSLINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RollQuantityMtr.
     * @return the RollQuantityMtr
     */
    public BigDecimal getRollQuantityMtr() {
        return (BigDecimal) getAttributeInternal(ROLLQUANTITYMTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RollQuantityMtr.
     * @param value value to set the  RollQuantityMtr
     */
    public void setRollQuantityMtr(BigDecimal value) {
        setAttributeInternal(ROLLQUANTITYMTR, value);
    }

    /**
     * Gets the attribute value for CUTABLE_WIDTH using the alias name CutableWidth.
     * @return the CUTABLE_WIDTH
     */
    public BigDecimal getCutableWidth() {
        return (BigDecimal) getAttributeInternal(CUTABLEWIDTH);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTABLE_WIDTH using the alias name CutableWidth.
     * @param value value to set the CUTABLE_WIDTH
     */
    public void setCutableWidth(BigDecimal value) {
        setAttributeInternal(CUTABLEWIDTH, value);
    }

    /**
     * Gets the attribute value for FINISH_WIDTH using the alias name FinishWidth.
     * @return the FINISH_WIDTH
     */
    public BigDecimal getFinishWidth() {
        return (BigDecimal) getAttributeInternal(FINISHWIDTH);
    }

    /**
     * Sets <code>value</code> as attribute value for FINISH_WIDTH using the alias name FinishWidth.
     * @param value value to set the FINISH_WIDTH
     */
    public void setFinishWidth(BigDecimal value) {
        setAttributeInternal(FINISHWIDTH, value);
    }

    /**
     * Gets the attribute value for KGS using the alias name Kgs.
     * @return the KGS
     */
    public BigDecimal getKgs() {
        return (BigDecimal) getAttributeInternal(KGS);
    }

    /**
     * Sets <code>value</code> as attribute value for KGS using the alias name Kgs.
     * @param value value to set the KGS
     */
    public void setKgs(BigDecimal value) {
        setAttributeInternal(KGS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GLM.
     * @return the GLM
     */
    public String getGLM() {
        //return (String) getAttributeInternal(GLM);
        ApplicationModule am = getApplicationModule();
        ViewObject inspPrcHeaderVO = (ViewObject)am.findViewObject("PwcInspectionProcessHeaderVO1");
        double result = 0;
        if (inspPrcHeaderVO!=null) {
            int GSM = Integer.parseInt(inspPrcHeaderVO.getCurrentRow().getAttribute("FinishGSM")!=null?inspPrcHeaderVO.getCurrentRow().getAttribute("FinalGsm").toString():"0");
            int finishWidth = getFinishWidth()!=null?getFinishWidth().intValue():0;
            result = GSM * (finishWidth/39.37);
        }
        return result+"";
    }
    

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GLM.
     * @param value value to set the  GLM
     */
    public void setGLM(String value) {
        setAttributeInternal(GLM, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PwcOdmInspPrcDyeFaultVO.
     */
    public RowIterator getPwcOdmInspPrcDyeFaultVO() {
        return (RowIterator)getAttributeInternal(PWCODMINSPPRCDYEFAULTVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PwcOdmInspPrcGreigeFaultVO.
     */
    public RowIterator getPwcOdmInspPrcGreigeFaultVO() {
        return (RowIterator)getAttributeInternal(PWCODMINSPPRCGREIGEFAULTVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PwcOdmInspPrcWeaveFaultVO.
     */
    public RowIterator getPwcOdmInspPrcWeaveFaultVO() {
        return (RowIterator)getAttributeInternal(PWCODMINSPPRCWEAVEFAULTVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PwcOdmInspPrcFaultEntriesVO.
     */
    public RowIterator getPwcOdmInspPrcFaultEntriesVO() {
        return (RowIterator)getAttributeInternal(PWCODMINSPPRCFAULTENTRIESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PwcOdmInsPrcFaultsTotalVO1.
     */
    public RowIterator getPwcOdmInsPrcFaultsTotalVO1() {
        return (RowIterator)getAttributeInternal(PWCODMINSPRCFAULTSTOTALVO1);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PwcInspectionProcessHeaderVO.
     */
    public Row getPwcInspectionProcessHeaderVO() {
        return (Row)getAttributeInternal(PWCINSPECTIONPROCESSHEADERVO);
    }

    /**
     * Sets the master-detail link PwcInspectionProcessHeaderVO between this object and <code>value</code>.
     */
    public void setPwcInspectionProcessHeaderVO(Row value) {
        setAttributeInternal(PWCINSPECTIONPROCESSHEADERVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GradesLOV1.
     */
    public RowSet getGradesLOV1() {
        return (RowSet)getAttributeInternal(GRADESLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RollNumberLOV1.
     */
    public RowSet getRollNumberLOV1() {
        return (RowSet)getAttributeInternal(ROLLNUMBERLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MachineNumberLOV1.
     */
    public RowSet getMachineNumberLOV1() {
        return (RowSet)getAttributeInternal(MACHINENUMBERLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
