package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 19 14:45:07 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcInspectionProcessLineVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PwcInspectionProcessLineVOImpl() {
    }

    /**
     * Returns the variable value for p_roll_number.
     * @return variable value for p_roll_number
     */
    public String getp_roll_number() {
        return (String)ensureVariableManager().getVariableValue("p_roll_number");
    }

    /**
     * Sets <code>value</code> for variable p_roll_number.
     * @param value value to bind as p_roll_number
     */
    public void setp_roll_number(String value) {
        ensureVariableManager().setVariableValue("p_roll_number", value);
    }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }


}
