package model.LOV;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 22 16:09:47 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RollNumberLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RollNumberLOVImpl() {
    }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }

    /**
     * Returns the bind variable value for p_insp_prc_id.
     * @return bind variable value for p_insp_prc_id
     */
    public String getp_insp_prc_id() {
        return (String)getNamedWhereClauseParam("p_insp_prc_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_insp_prc_id.
     * @param value value to bind as p_insp_prc_id
     */
    public void setp_insp_prc_id(String value) {
        
        setNamedWhereClauseParam("p_insp_prc_id", value);
    }
}
