package model.AM;

import model.AM.common.InspectionProcessAM;

import oracle.adf.share.ADFContext;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 10 14:48:01 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InspectionProcessAMImpl extends ApplicationModuleImpl implements InspectionProcessAM {
    /**
     * This is the default constructor (do not remove).
     */
    public InspectionProcessAMImpl() {
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl, String mfgOrgId) {
        System.out.println("orgid = "+orgId);
        ADFContext.getCurrent().getSessionScope().put("user_id", userId);
        ADFContext.getCurrent().getSessionScope().put("org_id", orgId);
        ADFContext.getCurrent().getSessionScope().put("resp_id", respId);
        ADFContext.getCurrent().getSessionScope().put("resp_appl_id", respAppl);
        ADFContext.getCurrent().getSessionScope().put("mfg_org_id", mfgOrgId);
        
        /*String   MfgOrgName = null;
                ViewObject mfgVO = this.getDBTransaction().createViewObjectFromQueryStmt("SELECT ORGANIZATION_ID,ORGANIZATION_NAME FROM ORG_ACCESS_V WHERE RESP_APPLICATION_ID = "+respAppl+" AND RESPONSIBILITY_ID = "+respId);
                //        ViewObject mfgVO = this.getDBTransaction().createViewObjectFromQueryStmt("SELECT ORGANIZATION_ID,ORGANIZATION_NAME FROM ORG_ACCESS_V WHERE RESP_APPLICATION_ID = 706 AND RESPONSIBILITY_ID = 51776");
                         if(mfgVO != null){
                             if(mfgVO.getRowCount() == 1){
                                 Row mfgRow = mfgVO.first();
                                 try{
                                     mfgOrgId = mfgRow.getAttribute(0).toString();
                                     ADFContext.getCurrent().getSessionScope().put("mfg_org_id", mfgOrgId);
                                 }catch(Exception e){
                                         ;
                                 }
                                 try{
                                     MfgOrgName = mfgRow.getAttribute(1).toString();
                                     ADFContext.getCurrent().getSessionScope().put("mfg_org_name", MfgOrgName);
                                 }catch(Exception e){
                                         ;
                                 }       
                             }    
                         }*/
                         System.out.println("mfg_org_id = "+mfgOrgId);
                //ADFContext.getCurrent().getSessionScope().put("mfg_org_id", mfgOrgId);
    }


    /**
     * Container's getter for PwcOdmInspPrcGreigeFaultVO1.
     * @return PwcOdmInspPrcGreigeFaultVO1
     */
    public ViewObjectImpl getPwcOdmInspPrcGreigeFaultVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcGreigeFaultVO1");
    }

    /**
     * Container's getter for PwcOdmInspPrcDyeFaultVO1.
     * @return PwcOdmInspPrcDyeFaultVO1
     */
    public ViewObjectImpl getPwcOdmInspPrcDyeFaultVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcDyeFaultVO1");
    }

    /**
     * Container's getter for PwcOdmInspPrcYarnFaultVO1.
     * @return PwcOdmInspPrcYarnFaultVO1
     */
    public ViewObjectImpl getPwcOdmInspPrcYarnFaultVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcYarnFaultVO1");
    }


    /**
     * Container's getter for PwcInspectionProcessHeaderVO1.
     * @return PwcInspectionProcessHeaderVO1
     */
    public ViewObjectImpl getPwcInspectionProcessHeaderVO1() {
        return (ViewObjectImpl)findViewObject("PwcInspectionProcessHeaderVO1");
    }

    /**
     * Container's getter for PwcInspectionProcessLineVO1.
     * @return PwcInspectionProcessLineVO1
     */
    public ViewObjectImpl getPwcInspectionProcessLineVO1() {
        return (ViewObjectImpl)findViewObject("PwcInspectionProcessLineVO1");
    }

    /**
     * Container's getter for PwcInspectionProcessVL.
     * @return PwcInspectionProcessVL
     */
    public ViewLinkImpl getPwcInspectionProcessVL() {
        return (ViewLinkImpl)findViewLink("PwcInspectionProcessVL");
    }

    /**
     * Container's getter for PwcOdmInspPrcDyeFaultVO2.
     * @return PwcOdmInspPrcDyeFaultVO2
     */
    public ViewObjectImpl getPwcOdmInspPrcDyeFaultVO2() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcDyeFaultVO2");
    }

    /**
     * Container's getter for InspPrcLineDyeFaultVL1.
     * @return InspPrcLineDyeFaultVL1
     */
    public ViewLinkImpl getInspPrcLineDyeFaultVL1() {
        return (ViewLinkImpl)findViewLink("InspPrcLineDyeFaultVL1");
    }


    /**
     * Container's getter for PwcOdmInspPrcGreigeFaultVO2.
     * @return PwcOdmInspPrcGreigeFaultVO2
     */
    public ViewObjectImpl getPwcOdmInspPrcGreigeFaultVO2() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcGreigeFaultVO2");
    }

    /**
     * Container's getter for InspPrcLineGreig1.
     * @return InspPrcLineGreig1
     */
    public ViewLinkImpl getInspPrcLineGreig1() {
        return (ViewLinkImpl)findViewLink("InspPrcLineGreig1");
    }

    /**
     * Container's getter for PwcOdmInspPrcYarnFaultVO2.
     * @return PwcOdmInspPrcYarnFaultVO2
     */
    public ViewObjectImpl getPwcOdmInspPrcYarnFaultVO2() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcYarnFaultVO2");
    }

    /**
     * Container's getter for InspPrcLineYarnFaultVL1.
     * @return InspPrcLineYarnFaultVL1
     */
    public ViewLinkImpl getInspPrcLineYarnFaultVL1() {
        return (ViewLinkImpl)findViewLink("InspPrcLineYarnFaultVL1");
    }


    /**
     * Container's getter for PwcOdmInspPrcDyeFaultVO3.
     * @return PwcOdmInspPrcDyeFaultVO3
     */
    public ViewObjectImpl getPwcOdmInspPrcDyeFaultVO3() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcDyeFaultVO3");
    }

    /**
     * Container's getter for PwcOdmInspPrcWeaveFaultVO1.
     * @return PwcOdmInspPrcWeaveFaultVO1
     */
    public ViewObjectImpl getPwcOdmInspPrcWeaveFaultVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcWeaveFaultVO1");
    }

    /**
     * Container's getter for PwcInspPrcWeaveFaultVL.
     * @return PwcInspPrcWeaveFaultVL
     */
    public ViewLinkImpl getPwcInspPrcWeaveFaultVL() {
        return (ViewLinkImpl)findViewLink("PwcInspPrcWeaveFaultVL");
    }

    /**
     * Container's getter for PwcInspectionProcessLineVO2.
     * @return PwcInspectionProcessLineVO2
     */
    public ViewObjectImpl getPwcInspectionProcessLineVO2() {
        return (ViewObjectImpl)findViewObject("PwcInspectionProcessLineVO2");
    }


    /**
     * Container's getter for PwcOdmInspPrcWeaveFaultVO2.
     * @return PwcOdmInspPrcWeaveFaultVO2
     */
    public ViewObjectImpl getPwcOdmInspPrcWeaveFaultVO2() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcWeaveFaultVO2");
    }

    /**
     * Container's getter for PwcInspPrcWeaveFaultVL1.
     * @return PwcInspPrcWeaveFaultVL1
     */
    public ViewLinkImpl getPwcInspPrcWeaveFaultVL1() {
        return (ViewLinkImpl)findViewLink("PwcInspPrcWeaveFaultVL1");
    }

    /**
     * Container's getter for PwcOdmInspPrcWeaveFaultVO3.
     * @return PwcOdmInspPrcWeaveFaultVO3
     */
   /* public ViewObjectImpl getPwcOdmInspPrcWeaveFaultVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcWeaveFaultVO1");
    }*/

    /**
     * Container's getter for PwcOdmInspPrcWeaveFaultVO3.
     * @return PwcOdmInspPrcWeaveFaultVO3
     */
    public ViewObjectImpl getPwcOdmInspPrcWeaveFaultVO3() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcWeaveFaultVO3");
    }

    /**
     * Container's getter for PwcOdmInspPrcFaultEntriesVO1.
     * @return PwcOdmInspPrcFaultEntriesVO1
     */
    public ViewObjectImpl getPwcOdmInspPrcFaultEntriesVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcFaultEntriesVO1");
    }

    /**
     * Container's getter for PwcInspectionProcessLineVO3.
     * @return PwcInspectionProcessLineVO3
     */
    public ViewObjectImpl getPwcInspectionProcessLineVO3() {
        return (ViewObjectImpl)findViewObject("PwcInspectionProcessLineVO3");
    }

    /**
     * Container's getter for PwcOdmInspPrcFaultEntriesVO2.
     * @return PwcOdmInspPrcFaultEntriesVO2
     */
    public ViewObjectImpl getPwcOdmInspPrcFaultEntriesVO2() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcFaultEntriesVO2");
    }

    /**
     * Container's getter for PwcOdmInspPrcLineFaultEntriesVL.
     * @return PwcOdmInspPrcLineFaultEntriesVL
     */
    public ViewLinkImpl getPwcOdmInspPrcLineFaultEntriesVL() {
        return (ViewLinkImpl)findViewLink("PwcOdmInspPrcLineFaultEntriesVL");
    }


    /**
     * Container's getter for PwcOdmInspPrcFaultEntriesVO3.
     * @return PwcOdmInspPrcFaultEntriesVO3
     */
    public ViewObjectImpl getPwcOdmInspPrcFaultEntriesVO3() {
        return (ViewObjectImpl)findViewObject("PwcOdmInspPrcFaultEntriesVO3");
    }

    /**
     * Container's getter for PwcOdmInspPrcLineFaultEntriesVL1.
     * @return PwcOdmInspPrcLineFaultEntriesVL1
     */
    public ViewLinkImpl getPwcOdmInspPrcLineFaultEntriesVL1() {
        return (ViewLinkImpl)findViewLink("PwcOdmInspPrcLineFaultEntriesVL1");
    }

    /**
     * Container's getter for PwcInspPrcFaultTypesVO1.
     * @return PwcInspPrcFaultTypesVO1
     */
    public ViewObjectImpl getPwcInspPrcFaultTypesVO1() {
        return (ViewObjectImpl)findViewObject("PwcInspPrcFaultTypesVO1");
    }

    /**
     * Container's getter for PwcInspectionProcessLineVO4.
     * @return PwcInspectionProcessLineVO4
     */
    public ViewObjectImpl getPwcInspectionProcessLineVO4() {
        return (ViewObjectImpl)findViewObject("PwcInspectionProcessLineVO4");
    }

    /**
     * Container's getter for PwcOdmInsPrcFaultsTotalVO1.
     * @return PwcOdmInsPrcFaultsTotalVO1
     */
    public ViewObjectImpl getPwcOdmInsPrcFaultsTotalVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmInsPrcFaultsTotalVO1");
    }

    /**
     * Container's getter for PwcOdmInspPrcLinesFaultTotalVL.
     * @return PwcOdmInspPrcLinesFaultTotalVL
     */
    public ViewLinkImpl getPwcOdmInspPrcLinesFaultTotalVL() {
        return (ViewLinkImpl)findViewLink("PwcOdmInspPrcLinesFaultTotalVL");
    }


    /**
     * Container's getter for PwcInspectionProcessLineVO5.
     * @return PwcInspectionProcessLineVO5
     */
    public ViewObjectImpl getPwcInspectionProcessLineVO5() {
        return (ViewObjectImpl)findViewObject("PwcInspectionProcessLineVO5");
    }

    /**
     * Container's getter for PwcOdmInsPrcFaultsTotalVO2.
     * @return PwcOdmInsPrcFaultsTotalVO2
     */
    public ViewObjectImpl getPwcOdmInsPrcFaultsTotalVO2() {
        return (ViewObjectImpl)findViewObject("PwcOdmInsPrcFaultsTotalVO2");
    }

    /**
     * Container's getter for PwcInspPrcLinesFaultsTotalVL.
     * @return PwcInspPrcLinesFaultsTotalVL
     */
    public ViewLinkImpl getPwcInspPrcLinesFaultsTotalVL() {
        return (ViewLinkImpl)findViewLink("PwcInspPrcLinesFaultsTotalVL");
    }

    /**
     * Container's getter for PwcOdmInsPrcFaultsTotalVO3.
     * @return PwcOdmInsPrcFaultsTotalVO3
     */
    public ViewObjectImpl getPwcOdmInsPrcFaultsTotalVO3() {
        return (ViewObjectImpl)findViewObject("PwcOdmInsPrcFaultsTotalVO3");
    }

    /**
     * Container's getter for PwcOdmInspPrcLinesFaultTotalVL1.
     * @return PwcOdmInspPrcLinesFaultTotalVL1
     */
    public ViewLinkImpl getPwcOdmInspPrcLinesFaultTotalVL1() {
        return (ViewLinkImpl)findViewLink("PwcOdmInspPrcLinesFaultTotalVL1");
    }

    /**
     * Container's getter for FinishingJobNumberLOV1.
     * @return FinishingJobNumberLOV1
     */
    public ViewObjectImpl getFinishingJobNumberLOV1() {
        return (ViewObjectImpl)findViewObject("FinishingJobNumberLOV1");
    }

    /**
     * Container's getter for GradesLOV1.
     * @return GradesLOV1
     */
    public ViewObjectImpl getGradesLOV1() {
        return (ViewObjectImpl)findViewObject("GradesLOV1");
    }

    /**
     * Container's getter for RollNumberLOV1.
     * @return RollNumberLOV1
     */
    public ViewObjectImpl getRollNumberLOV1() {
        return (ViewObjectImpl)findViewObject("RollNumberLOV1");
    }

    /**
     * Container's getter for MachineNumberLOV1.
     * @return MachineNumberLOV1
     */
    public ViewObjectImpl getMachineNumberLOV1() {
        return (ViewObjectImpl)findViewObject("MachineNumberLOV1");
    }
}
