package model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 15 15:09:47 PKT 2018
// ---------------------------------------------------------------------
public interface InspectionProcessAM extends ApplicationModule {
    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl, String mfgOrgId);
}
